UI update
rachelpr/LeafSmart pull request #84
Opened 2022-08-14 03:59 UTC by b1u3too

Hi pals! 
Knocked a couple more things off my wishlist tonight. This will need an `npm i` for sure! 

These can absolutely be finessed if they're "close but no cigar", or yeeted if we hate 'em, however I'd love for you to have a look at:
- on loadup before search, there is now a Welcome widget with our icon and animated typewriter text pitching what the app actually does
- if we search for a data with nothing at the other end of our Event or Quality of Life endpoints, a simple little component will load with icons from a random 1 of 5 icons from [unDraw](https://undraw.co/illustrations) that have been customized to match our colour theme. Icons can absolutely be subbed out/added to easily. I think it's nice to see confirmation that yes, there really is nothing coming... and the random illustrations inject a little fun into something that's otherwise a bit of a bummer.

**this should be a draft review**, as I'd like to rebase it and make sure everything's compatible with the favourite hookup before merging in if we want to roll with these additions!

2022-08-14 11:43 UTC, MGS31 requested changes
These adjustments look awesome! I especially like the blank widget images you went with! 

Only points of concern is the welcome widget seems...... small like its not immediately sitting perfectly with me, wondering if we could make it a box that fits like the whole page or something? instead of tucked into the corner like it is now? Thoughts?

2022-08-14 15:21 UTC, b1u3too commented
> These adjustments look awesome! I especially like the blank widget images you went with!
> 
> Only points of concern is the welcome widget seems...... small like its not immediately sitting perfectly with me, wondering if we could make it a box that fits like the whole page or something? instead of tucked into the corner like it is now? Thoughts?

Right? It's definitely sort of tiny, and I was hoping to lean into both you and Rachel to take it from "it's there" to "WHAT A BEAUT". 

You both have such a great eye for design and layout-- the thing I _know_ I wanted was a bigger image of our logo and some kind of animated text that would explain what our app is and does for folks, sucking them into giving it at least one try. The typewriter thing's a little cliche, but I think it jives with our vibe. 

I'm going to figure out how to make it cover a larger portion of the page without unsettling the seat of the search bar -- so that when we can get together and discuss, I tweak it live to be a design y'all like more! :)

2022-08-15 00:20 UTC, MGS31 approved these changes

2022-08-15 01:26 UTC, rachelpr approved these changes
Love these! We can fiddle with this as needed :)

2022-08-15 01:28 UTC, merged